# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
# A wrapper to take multiple resources and pass each one to create_resources
# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'hash_resources::hash_resources') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    hash = args[0]
    raise Puppet::ParserError, "Must provide a hash" unless hash.is_a? Hash

    Puppet::Parser::Functions.autoloader.load(:create_resources) \
      unless Puppet::Parser::Functions.autoloader.loaded?(:create_resources)

    hash.each do |resource, objects|
      function_create_resources([resource, objects])
    end
  
  end
end
